name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create dist directory
        run: mkdir -p dist

      - name: Generate snake.svg (theme-neutral)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: prithesh07
          outputs: |
            dist/snake.svg
        env:
          COLOR_BACK: "00000000"
          COLOR_DOT: "#888888"
          COLOR_RING: "#5f9ea0"
          COLOR_SNAKE: "#9370DB"

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dist/snake.svg'
          message: 'Generate theme-neutral snake animation'
          push: true
          default_author: github_actions

      - run: git status

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
